version: '2'

services:
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq-curiosity-sample"
    environment:
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5674:5672"
    labels:
      NAME: "rabbitmq-curiosity-sample"
