# Configures logging
Log:
  # Path to NLog.config file
  LogConfigurationPath: ./NLog.config
  # Path to logs out directory
  LogOutputDirectory: ./logs
  
QueueName: test
  
# Connection to RabbitMQ
RabbitMQ:
  HostName: localhost
  UserName: test
  Password: test
  Port: 5674
