name: Publish packages to Nuget

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Pack
      shell: bash
      with:
        nugetApiKey: ${{ secrets.NUGETAPIKEY }}
      run: |
        ./build.sh -t GitHub --nugetApiKey=$nugetApiKey
