Urls: http://127.0.0.1:39122

Log:
  LogConfigurationPath: ./NLog.config
  LogOutputDirectory: ./log

# Name collection of the fields the data in which we want to hide
SensitiveDataFieldNames:
  - password
  - passwordConfirmation
